// Mock data for demo deployment (no database required)

export const mockCalendars = [
  { id: '1', name: 'City Events', slug: 'city-events', color: '#002D72', isActive: true },
  { id: '2', name: 'Parks & Recreation', slug: 'parks-recreation', color: '#16a34a', isActive: true },
  { id: '3', name: 'Library', slug: 'library', color: '#7c3aed', isActive: true },
  { id: '4', name: 'Community Center', slug: 'community', color: '#0891b2', isActive: true },
]

export const mockCategories = [
  { id: '1', name: 'Sports & Fitness', slug: 'sports-fitness' },
  { id: '2', name: 'Arts & Culture', slug: 'arts-culture' },
  { id: '3', name: 'Education', slug: 'education' },
  { id: '4', name: 'Family', slug: 'family' },
  { id: '5', name: 'Community', slug: 'community' },
]

export const mockTags = [
  { id: '1', name: 'Free', slug: 'free' },
  { id: '2', name: 'Outdoor', slug: 'outdoor' },
  { id: '3', name: 'Indoor', slug: 'indoor' },
  { id: '4', name: 'Registration Required', slug: 'registration-required' },
]

export const mockAgeGroups = [
  { id: '1', name: 'All Ages', slug: 'all-ages' },
  { id: '2', name: 'Kids (0-12)', slug: 'kids' },
  { id: '3', name: 'Teens (13-17)', slug: 'teens' },
  { id: '4', name: 'Adults (18+)', slug: 'adults' },
  { id: '5', name: 'Seniors (55+)', slug: 'seniors' },
]

export const mockVenues = [
  { id: '1', name: 'Mansfield Activities Center', address: '106 S Wisteria St, Mansfield, TX' },
  { id: '2', name: 'Katherine Rose Memorial Park', address: '3001 E Broad St, Mansfield, TX' },
  { id: '3', name: 'Mansfield Public Library', address: '104 S Wisteria St, Mansfield, TX' },
  { id: '4', name: 'Big League Dreams Sports Park', address: '500 Heritage Pkwy, Mansfield, TX' },
  { id: '5', name: 'Hawaiian Falls Waterpark', address: '490 Heritage Pkwy, Mansfield, TX' },
]

export const mockHosts = [
  { id: '1', name: 'Parks & Recreation Dept', email: 'parks@mansfield.gov' },
  { id: '2', name: 'Mansfield Public Library', email: 'library@mansfield.gov' },
  { id: '3', name: 'Community Services', email: 'community@mansfield.gov' },
]

const today = new Date()
const addDays = (days: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() + days)
  return d.toISOString()
}

// Helper to create relational structure matching Prisma's output format
const wrapCalendar = (calendar: typeof mockCalendars[0]) => [{ calendar }]
const wrapCategories = (categories: typeof mockCategories) => categories.map(category => ({ category }))
const wrapTags = (tags: typeof mockTags) => tags.map(tag => ({ tag }))
const wrapAgeGroups = (ageGroups: typeof mockAgeGroups) => ageGroups.map(ageGroup => ({ ageGroup }))

export const mockEvents = [
  {
    id: '1',
    title: 'Summer Concert in the Park',
    slug: 'summer-concert-park',
    shortDescription: 'Free outdoor concert with local bands and food trucks',
    longDescription: 'Join us for a free outdoor concert featuring local bands and food trucks. Bring your lawn chairs and blankets!',
    startDate: addDays(2),
    endDate: addDays(2),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: true,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[1]),
    calendarId: '2',
    venue: mockVenues[1],
    venueId: '2',
    host: mockHosts[0],
    hostId: '1',
    categories: wrapCategories([mockCategories[1]]),
    tags: wrapTags([mockTags[0], mockTags[1]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[0]]),
  },
  {
    id: '2',
    title: 'Youth Basketball League Registration',
    slug: 'youth-basketball-registration',
    shortDescription: 'Fall youth basketball league for ages 6-14',
    longDescription: 'Register your child for the fall youth basketball league. Ages 6-14 welcome. Season runs September through November.',
    startDate: addDays(5),
    endDate: addDays(5),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: false,
    isFree: false,
    cost: 75,
    calendars: wrapCalendar(mockCalendars[1]),
    calendarId: '2',
    venue: mockVenues[3],
    venueId: '4',
    host: mockHosts[0],
    hostId: '1',
    categories: wrapCategories([mockCategories[0]]),
    tags: wrapTags([mockTags[3]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[1], mockAgeGroups[2]]),
  },
  {
    id: '3',
    title: 'Storytime for Toddlers',
    slug: 'storytime-toddlers',
    shortDescription: 'Weekly storytime with songs and crafts for ages 2-4',
    longDescription: 'Weekly storytime session for toddlers ages 2-4. Includes songs, rhymes, and a craft activity.',
    startDate: addDays(1),
    endDate: addDays(1),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: false,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[2]),
    calendarId: '3',
    venue: mockVenues[2],
    venueId: '3',
    host: mockHosts[1],
    hostId: '2',
    categories: wrapCategories([mockCategories[2], mockCategories[3]]),
    tags: wrapTags([mockTags[0], mockTags[2]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[1]]),
  },
  {
    id: '4',
    title: 'City Council Meeting',
    slug: 'city-council-meeting',
    shortDescription: 'Monthly city council meeting - open to public',
    longDescription: 'Regular monthly meeting of the Mansfield City Council. Open to the public.',
    startDate: addDays(7),
    endDate: addDays(7),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: false,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[0]),
    calendarId: '1',
    venue: mockVenues[0],
    venueId: '1',
    host: mockHosts[2],
    hostId: '3',
    categories: wrapCategories([mockCategories[4]]),
    tags: wrapTags([mockTags[0], mockTags[2]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[3]]),
  },
  {
    id: '5',
    title: 'Senior Fitness Class',
    slug: 'senior-fitness-class',
    shortDescription: 'Low-impact fitness for seniors - improve balance and strength',
    longDescription: 'Low-impact fitness class designed for seniors. Improve balance, flexibility, and strength in a fun group setting.',
    startDate: addDays(3),
    endDate: addDays(3),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: false,
    isFree: false,
    cost: 10,
    calendars: wrapCalendar(mockCalendars[3]),
    calendarId: '4',
    venue: mockVenues[0],
    venueId: '1',
    host: mockHosts[0],
    hostId: '1',
    categories: wrapCategories([mockCategories[0]]),
    tags: wrapTags([mockTags[2]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[4]]),
  },
  {
    id: '6',
    title: 'Art in the Park Festival',
    slug: 'art-in-the-park',
    shortDescription: 'Annual arts festival with local artists and live demos',
    longDescription: 'Annual arts festival featuring local artists, live demonstrations, food vendors, and activities for all ages.',
    startDate: addDays(10),
    endDate: addDays(11),
    isAllDay: true,
    status: 'PUBLISHED',
    isFeatured: true,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[0]),
    calendarId: '1',
    venue: mockVenues[1],
    venueId: '2',
    host: mockHosts[2],
    hostId: '3',
    categories: wrapCategories([mockCategories[1], mockCategories[3]]),
    tags: wrapTags([mockTags[0], mockTags[1]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[0]]),
  },
  {
    id: '7',
    title: 'Book Club Meeting',
    slug: 'book-club-meeting',
    shortDescription: "Discussing 'The Great Gatsby' - new members welcome",
    longDescription: "This month we're discussing 'The Great Gatsby' by F. Scott Fitzgerald. New members welcome!",
    startDate: addDays(8),
    endDate: addDays(8),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: false,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[2]),
    calendarId: '3',
    venue: mockVenues[2],
    venueId: '3',
    host: mockHosts[1],
    hostId: '2',
    categories: wrapCategories([mockCategories[2]]),
    tags: wrapTags([mockTags[0], mockTags[2]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[3]]),
  },
  {
    id: '8',
    title: 'Splash Pad Grand Opening',
    slug: 'splash-pad-opening',
    shortDescription: 'New splash pad opening with free snow cones',
    longDescription: 'Celebrate the grand opening of our new splash pad! Free snow cones and activities for kids.',
    startDate: addDays(14),
    endDate: addDays(14),
    isAllDay: false,
    status: 'PUBLISHED',
    isFeatured: true,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[1]),
    calendarId: '2',
    venue: mockVenues[4],
    venueId: '5',
    host: mockHosts[0],
    hostId: '1',
    categories: wrapCategories([mockCategories[3]]),
    tags: wrapTags([mockTags[0], mockTags[1]]),
    ageGroups: wrapAgeGroups([mockAgeGroups[0]]),
  },
]

export const mockPendingEvents = [
  {
    id: 'p1',
    title: 'Community Garage Sale',
    slug: 'community-garage-sale',
    shortDescription: 'Annual neighborhood garage sale',
    longDescription: 'Annual neighborhood garage sale. Over 50 families participating!',
    startDate: addDays(20),
    endDate: addDays(20),
    isAllDay: true,
    status: 'PENDING',
    isFeatured: false,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[0]),
    calendarId: '1',
    submitterName: 'John Smith',
    submitterEmail: 'john.smith@email.com',
  },
  {
    id: 'p2',
    title: 'Dog Adoption Event',
    slug: 'dog-adoption-event',
    shortDescription: 'Meet adoptable dogs from local shelter',
    longDescription: 'Local shelter bringing adoptable dogs. Meet your new best friend!',
    startDate: addDays(15),
    endDate: addDays(15),
    isAllDay: false,
    status: 'PENDING',
    isFeatured: false,
    isFree: true,
    calendars: wrapCalendar(mockCalendars[1]),
    calendarId: '2',
    submitterName: 'Sarah Johnson',
    submitterEmail: 'sarah.j@email.com',
  },
  {
    id: 'p3',
    title: 'Photography Workshop',
    slug: 'photography-workshop',
    shortDescription: 'Digital photography basics workshop',
    longDescription: 'Learn basics of digital photography. Bring your own camera.',
    startDate: addDays(18),
    endDate: addDays(18),
    isAllDay: false,
    status: 'PENDING',
    isFeatured: false,
    isFree: false,
    cost: 25,
    calendars: wrapCalendar(mockCalendars[2]),
    calendarId: '3',
    submitterName: 'Mike Chen',
    submitterEmail: 'mike.chen@email.com',
  },
]

export const mockUsers = [
  { id: '1', name: 'Sarah Johnson', email: 'sarah.johnson@mansfield.gov', role: 'ADMIN' },
  { id: '2', name: 'Emily Chen', email: 'emily.chen@mansfield.gov', role: 'EDITOR' },
  { id: '3', name: 'Mike Thompson', email: 'mike.thompson@mansfield.gov', role: 'CONTRIBUTOR' },
  { id: '4', name: 'Lisa Park', email: 'lisa.park@mansfield.gov', role: 'EDITOR' },
]
